### ISSUE TITLE
mulF.cl implemented x + y

### ISSUE THREAD

**Issue by TBodyAltra** [ROCm/ROCm-Device-Libs#98]
If you look into mulF.cl carefully, you will notice:

#include "mathF.h"

CONSTATTR float
MATH_MANGLE(mul_rte)(float x, float y)
{
    **return x + y;**
}

**Comment by b-sumner** [comment]
Good grief!  Thanks for pointing this out, and apologies for any headaches it caused.  Will fix ASAP.

**Comment by b-sumner** [comment]
Fix will not be in ROCm 5.7.

**Comment by TBodyAltra** [comment]
Wondering do you guys have any test for ocml functions? This typo is so apparent. I want to test too.

**Comment by TBodyAltra** [comment]
@b-sumner thanks

**Comment by lamb-j** [comment]
Fixed here:

https://github.com/ROCm/llvm-project/commit/8efb5d685b7cbad40dfb8c73745301b0348a9d95
